Change reclass revision
Mirantis/stacklight-salt-model pull request #28
Opened 2017-02-17 11:58 UTC by dkalashnik

2017-02-22 10:10 UTC, simonpasquier approved these changes

2017-03-01 15:35 UTC, SwannCroiset requested changes

2017-03-01 15:35 UTC, SwannCroiset commented on classes/cluster/mk22_lab_dvr/infra/config.yml
> +    reclass_data_repository: "git@github.com:dkalashnik/stacklight-salt-model.git"
opss

2017-03-01 15:35 UTC, SwannCroiset commented on classes/cluster/mk22_lab_dvr/openstack/compute.yml
> +- system.linux.system.repo.mos92
did you test successfully 9.2 packages ?

2025-05-27 13:37 UTC, closed without merging