[DO NOT MERGE] Add k8s cluster definition
Mirantis/stacklight-salt-model pull request #35
Opened 2017-02-21 16:34 UTC by SwannCroiset

mainly inspired from https://github.com/mceloud/k8s-salt-model

* not tested a complete bootstrap
* missing at least: rsyslog

2017-02-24 11:03 UTC, simonpasquier approved these changes

2017-02-24 12:11 UTC, obourdon requested changes
Just minor remark on the not-executable status of one script.
Otherwise tested successfully on my own env

2017-02-24 12:11 UTC, obourdon commented on scripts/bootstrap_k8s.sh
> +#!/bin/bash -x
Script should be made executable

2017-02-27 14:43 UTC, obourdon approved these changes

2017-03-01 15:30 UTC, SwannCroiset commented on scripts/bootstrap_k8s.sh
> +#!/bin/bash -x
done

2017-03-01 15:31 UTC, merged